version: '3'

services:
  efpractice:
    image: efpractice
    build:
      context: .
      dockerfile: EFPractice/Dockerfile
  db:
    image: mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sc4m@th
