version: '3'

services:
  efpractice:
    image: efpractice
    build:
      context: .
      dockerfile: EFPractice/Dockerfile
    environment:
      ConnectionString: "Server=192.168.99.100;Database=test;Uid=root;Pwd=sc4m@th;"
  db:
    image: mysql
    restart: always
    volumes: 
      - data:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sc4m@th

volumes:
  data:
